name: Update mappings

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Fetch mappings
        id: mappings
        run: deno run --allow-all mod.ts

      - name: Commit and push
        id: commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add mappings.json
          git commit -m 'chore: update mappings'
          git push origin main
          echo "sha=$(git rev-parse main)" >> $GITHUB_OUTPUT
      
      - uses: peter-evans/commit-comment@v2
        if: steps.commit.outputs.changes_detected == 'true'
        with:
          sha: ${{ steps.commit.outputs.sha }}
          body: ${{ steps.mappings.outputs.commit-comments }}
